# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true
[[social]]
identifier = "bluesky"
name = "Bluesky"
url = "https://phasewalk1.bsky.social"
weight = 3

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/phasewalk1"
weight = 1

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/phasewalk1"
weight = 2

[social.params]
icon = "brand-twitter"

